# -*- coding: utf-8 -*-
"""comando_input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQxkSHL91d93SummZMNTRSuK3c_HqTtZ

# COMANDO IMPUT

A FUNÇÃO INPUT() RECEBE COMO PARÂMETTRO UMA STRING QUE SERÁ MOSTRADA COMO AUXILIO AO USUÁRIO, GERALMENTE O INFORMANDO QUE TIPO DE Dado o programa está aguardando receber.\
input()
"""

# input
input(' alguma mensagem!!!')

# form
Nome = input('Qual o seu nome?')
Idade = input('Qual a sua idade?')

print(Nome + ' ' + Idade + ' anos')



