# -*- coding: utf-8 -*-
"""nomeaçãodevariáveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YvM2ZApqM4WiaTl8QYRzAAlJsgm17cq

# Nomeaçao de variáveis

podemos nomear variáveis e tipos de dados de diversas fomras:

declar variáveis em uma única linha de comando

1.   Item da lista
2.   Item da lista


atribuir um valor á diversas variaveis
declarar usando uma lista
combinar variaveis
operar com operadores matematicos
"""

# nomeando
Laranja, melao, limao = 1, 2, 3

print(Laranja, melao, limao)

#nomeando
Morango = uva = kiwi = 100
print(Morango, uva, kiwi)

#nomear com listas
Lista_de_carros =  ['gol', 'celta', 'uno']
marca_01, marca_02, marca_03 = Lista_de_carros

print(Lista_de_carros)

#COMBINAR VARIAVEIs
nome = 'guilherme'
sobrenome = 'ferreira'
nome_completo = nome + ' ' + sobrenome
print(nome_completo)

#experimento
nome = 'Guilherme '
idade = str( 27 )
nome + idade + ' anos'

investimento = 1000
taxa_de_juros = float('0.2')
print( investimento * taxa_de_juros )

valor_ganhado = (investimento * taxa_de_juros) + investimento
print( valor_ganhado )

investimento = 1000
taxa_de_juros = float('0.2')
print( investimento * taxa_de_juros )

valor_ganhado = (investimento * taxa_de_juros) + investimento
print( valor_ganhado )

