# -*- coding: utf-8 -*-
"""Operadores_de_comparação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wn6OXEaCgE2xCi2rRxGuYdyJS5485WPL

# operadores de comparação

. == igual a\
. != diferente\
. > maior\
. < menor\
. >= maior igual\
. <= menor igual
"""

10 == 10

10 == 8

10 != 8

10 != 10

9 == 2

9 > 3

9 < 6

9 <= 9

10 >= 10

