# -*- coding: utf-8 -*-
"""Operadores-lógicos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTOiQ1eV0Zm5nundRE7HVzHZMtIxnyCn

# Operadores lógicos

-- usados para combinar instrucoes condicionais

1. and(retorna True se ambas as declaracoes forem verdadeiras)
2. or ( retorna True se uma das declaracoes for verdadeira)
3. not ( inverte o resultado, retorna False se o resultado for verdadeiro)
"""

10 > 2 and 10 > 3

10 > 2 and 10 > 20

10 > 5 or 10 > 20

10 == 2 or 10 < 20

Lista = [1,2,3,4]

10  not in  Lista

