# -*- coding: utf-8 -*-
"""Operadores_de_associação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pEPfW6GPxt9GlKMXo-_sN8wOTpVe9UK5

# Operadores de associação

são usados para testar se uma sequência é apresentada em um objeto:
1. in ( retorna true se uma sequencia com o valor especificado estiver presente no objeto)
2. not in (retona true se uma sequencia com o valor especificado não estiver presente no objeto)
"""

Lista_ações = ['Magalu', 'Via' , 'Carrefour']

'Via' in Lista_ações

'zz' in Lista_ações

'zz' not in Lista_ações

'll'  not in Lista_ações

