# -*- coding: utf-8 -*-
"""operadores_de_identidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfLSA_7LnJTeK3b22aWqrKR0nUnfSg0S

# Operadores de identidade

sao usados para comparar os objetos, não se forem iguais, mas se forem realmente o mesmo objeto, com a mesma localização de memoria

1. is (Retorna True se ambas as variáveis forem o mesmo objeto)
2. is not ( retorna True se ambas as variáveis não forem o mesmo objeto)
"""

String_01 = ' Olá mundão!'
String_02 = ' Olá mundão!'
type(String_01) == type(String_02)

type(String_01) is not type(String_02)

