# -*- coding: utf-8 -*-
"""operadores matemáticos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DIApT9slWBOPsbxMBpaeVP10uzqCF8XS

# Operadores matematicos

os operadores são usados para realizar operações em variáveis e valores:

1.SOMA \
2.SUBTRAÇÃO\
3.MULTIPLICACAO\
4.DIVISAO\
5.EXPONENCIACAO\
6.RESTO DA DIVISAO\
7.DIVISAO DE CHÃO
"""

#SOMA
1 + 3 + 4

#SUBTRACAO
4-4

#MULTIPLICACAO
4*4

#DIVISAO
4/4

# exponenciacao

2 ** 3 #(2.2.2)

# resto da divisao
3 % 4

# divisao de chao
3 // 4

# priorizacao
(2 + 2) * 5

2 + 2 * 5

