# -*- coding: utf-8 -*-
"""Scrip_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDSYAPKsFgfzmcHeKJdTXkNNj-9XRm8n
"""

print('bem vindo ao curso de python')

print("Bem vindo ao curso de python")

#comentário !!!!

print('olá mundão! \nPulou  \n uma \n Linha!' )

