# -*- coding: utf-8 -*-
"""tiposdedados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hY-js9fJXfmajiEg4sffSMpdV7a6lRV_

# Tipos de dados
1. lista- sao criadas usando [] (colchete)\
2. tuplas sao criadas usando () (parenteses)
3. dicionários - sao criadas usando {} (chaves)

eses tipos de dados podem receber qualquer tipo de informação, inclusive operacao aritméticas
"""

# listas
Lista_exemplo_01 = [1,2,3,4,5]
print(Lista_exemplo_01)

# lista de nome
lista_exemplo_02 = ['nome', 'sobrenome', 'idade', 4 , 4]
print(lista_exemplo_02)

lista_exemplo_03 =[1, 'texto', True,[1, 2, 3]]
print(lista_exemplo_03)

# tuplulas são imutaveis
tupla_exemplo_01 = (1,2,3,4,5)
tupla_exemplo_02 = (1, 'texto', True,1, 2, 3)
print(tupla_exemplo_01, tupla_exemplo_02)

tupla_exemplo_01, tupla_exemplo_02

# dicionario
dicionario = {
    'index': 'valor',
    'id' : 1,
    'id' : 2,
    'nome' : 'nome',
    'sobrenome' : 'sobrenome',
    'lista' : Lista_exemplo_01,
    'tupla' : tupla_exemplo_01,
    'dicionario' : dicionario
}
print(dicionario)

