# -*- coding: utf-8 -*-
"""variáveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jk1KluHjLCLAiC4RTC70tGSspOWLqYHa

# Variáveis
Variaveis são contêiners para armazenar valores de dados.\
uma variável é criada no momento em que você atribui um valor a ela.
"""

# variáveis

Nome = 'Guilherme'

Nome

Qualuqer_nome_que_quiser = 'variavel'

Qualuqer_nome_que_quiser

# variáveis de texto
var_texto1 = 'qualquer texto teste'
var_texto = str('qualquer texto')

print(var_texto1)

# variaveis numericas
Var_Inteiro_01 = 100
var_Inteiro_02 = int(200)

print(Var_Inteiro_01, var_Inteiro_02)

# variaveis flutuantes decimais

Var_flutuante_o1 = 100.50
Var_flutuante_02 = float(10.50)

print(Var_flutuante_o1, Var_flutuante_02)

# variaveis boleanas

var_boleano_01 = True
var_boleano_02 = False

print(var_boleano_01, var_boleano_02)